---
# Stolen from: https://github.com/ThePrimeagen/ansible/blob/master/tasks/nvim-setup.ym
- name: Remove neovim
  shell: rm -rf ~/neovim
- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ ansible_env.HOME }}/neovim"
    version: stable
    force: true
  register: neovim_git
- name: Run distclean in neovim source dir
  shell: "cd {{ ansible_env.HOME }}/neovim && make distclean"
  when: neovim_git.changed
- name: Build neovim
  shell: "cd {{ ansible_env.HOME }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  when: neovim_git.changed
- name: Install neovim
  become: true
  shell: "cd {{ ansible_env.HOME }}/neovim && make install"
  when: neovim_git.changed
# - name: Neovim Plugin Development 1
#  become: true
#  apt: name=luarocks
# - name: Neovim Plugin Development 2 luacheck
#  become: true
#  shell: luarocks install luacheck
- name: Install plugins
  shell: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"
  when: neovim_git.changed
