---
# defaults file for dots
user: "{{ lookup('env', 'USER') }}"

essential_packages:
  - zsh
  - vim
  - tmux
  - build-essential
  - git
  - gpg-agent
  - unzip
  - unrar
  - wget
  - rsync
  - apt-transport-https
  - tree
  - ca-certificates
  - curl
  - jq
  - python3
  - python3-pip
  - python3-venv
  - python3-setuptools
  - tig
  - dnsutils
  - gnupg
  - lsb-release

additional_packages:
  - ranger
  - mupdf
  - pandoc
  - kubectl
  - terraform
  - shellcheck
  - ninja-build
  - gettext
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config
  - unzip
  - curl
  - doxygen
  - terraform-ls
  - ripgrep
  - fd-find
  - sshpass
  - packer
  - vagrant
  - bat
  - clang
  - texlive-latex-recommended
  - texlive-latex-extra
  - strace
  - maven
  - wslu
  - azure-cli

pip_packages:
  - setuptools
  - molecule
  - molecule-docker
  - pre-commit
  - yamllint
  - github3.py
  - neovim
  - ipython
  - tldr

npm_packages:
  - neovim
  - yaml-language-server
  - pyright
  - typescript
  - vscode-langservers-extracted
  - ts-node
  # Breaks stuff
  # - yarn
