#!/usr/bin/env bash
# Hats off to ThePrimeagen
# https://raw.githubusercontent.com/ThePrimeagen/.dotfiles/master/bin/.local/scripts/tmux-sessionizer
# https://www.github.com/ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Add dirs to below list for more searching
    selected=$(find ~/projects ~/work ~ -mindepth 1 -maxdepth 1 -type d | fzf-tmux)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
